config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :posts, except: :destroy do
    member do
      post 'vote'
    end

    resources :comments, only: :create do
      member do 
        post 'vote'
      end
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  before_save :generate_slug

  def generate_slug
    self.slug = self.name.gsub(' ', '-')
  end

  def to_param
    self.slug
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  belongs_to :post
  has_many :votes, as: :voteable

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :url, presence: true

  before_save :generate_slug

  def generate_slug
    self.slug = self.title.gsub(' ', '-').downcase
  end

  def to_param
    self.slug
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 6}

  before_save :generate_slug

  def generate_slug
    self.slug = self.username.gsub(' ', '-').downcase
  end

  def to_param
    self.slug
  end

  def admin?
    self.role == 'admin'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  belongs_to :voteable, polymorphic: true

  validates :creator, uniqueness: { scope: :voteable, message: "Your vote was previously counted!" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :update_access, :total_votes

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = 'Must be logged in for that action'
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end

  def access_denied
    flash[:error] = "You do not have access to that action"
    redirect_to root_path
  end

  def update_access(obj)
    obj.creator == current_user
  end

  def total_votes(obj)
    plus_votes(obj) - minus_votes(obj)
  end

  def plus_votes(obj)
    obj.votes.where(vote: true).count
  end

  def minus_votes(obj)
    obj.votes.where(vote: false).count
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :require_user, except: [:index, :show]
  before_action :require_admin, only: [:new, :create]

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was created!'
    else
      render 'new'
    end
  end

  def new
    @category = Category.new
  end

  def show

  end

  private
    def set_category
      @category = Category.find_by(slug: params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find_by(slug: params[:post_id])
    @comment.post = @post
    @comment.creator = current_user

    if @comment.save
      redirect_to @post, notice: "Comment Added!"
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.new(vote: params[:vote], voteable: @comment, creator: current_user)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to :back, notice: 'Vote was counted!' }
        format.js
      else
        format.html do 
          flash[:error] = @vote.errors[:creator].first
          redirect_to :back
        end
        format.js 
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :vote, :edit, :update]
  before_action :require_user, except: [:index, :show]

  def index
    @posts = Post.all.sort_by {|x| total_votes(x)}.reverse 
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      redirect_to @post, notice: 'Post was created!'
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def update
    require_admin unless update_access(@post)

    if @post.update(post_params)
      redirect_to @post, notice: 'Post was updated!'
    else
      render 'edit'
    end
  end

  def edit
    require_admin unless update_access(@post)
  end

  def show
    @comment = Comment.new
  end

  def vote
    @vote = Vote.new(vote: params[:vote], voteable: @post, creator: current_user)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to :back, notice: 'Vote was counted!' }
        format.js
      else
        format.html do 
          flash[:error] = @vote.errors[:creator].first
          redirect_to :back
        end
        format.js 
      end
    end

  end

  private
    def set_post
      @post = Post.find_by(slug: params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :url, :description, category_ids: [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome, #{user.username}"
    else
      @error = "There was an error in your username or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logout successful"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Registration Successful!"
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :timezone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_url(url)
    url.start_with?("http://") ? url : "http://#{url}"
  end

  def format_timestamp(ts)
    if logged_in? && !current_user.timezone.blank?
      ts = ts.in_time_zone(current_user.timezone)
    end

    ts.strftime("%m/%d/%Y %l:%M%P %Z")
  end

end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />
  <%= f.submit %>
<% end %>

app/views/categories/new.html.erb
<h3> New Category! </h3>

<%= render 'form' %>

app/views/categories/show.html.erb
<h4> <%= @category.name %> </h4>

<ul>
  <% @category.posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
  <% end %>
</ul>

app/views/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes").html("<%= total_votes(@comment) %>")

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>

  <% if logged_in? %>
    <li>
      <%= link_to 'New Post', new_post_path %>
    </li>
    <% if current_user.admin? %>
      <li>
        <%= link_to 'New Category', new_category_path %>
      </li>
    <% end %>
    <li>
      <%= link_to "Logged in as: #{current_user.username}", edit_user_path(current_user) %>
    <li>
      <%= link_to 'Log Out', logout_path %>
    </li>
  <% else %>
    <li>
      <%= link_to 'Register', register_path %>
    </li>
    <li>
      <%= link_to 'Login', login_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header id='header-bar'>
      <div class="navbar">
        <div class="navbar-inner" >
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<%= form_for(@post) do |f| %>
  <%= f.label :categories %>
  <%= f.collection_select(:category_ids, Category.all, :id, :name, 
        {:selected => @post.categories.map{|cat| cat.id} }, {:multiple => true}) %>
  <br />
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br />
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br />
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br />
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h3>Edit Post!</h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3>Welcome to Postit!</h3>

<% @posts.each do |post| %>
  <table class='table'>
    <tr class='info'>
      <td class='span2'>
        <% if logged_in? %>
          <%= link_to vote_post_path(post, vote: 'true'), method: 'POST', remote: true do %>
            <i class='icon-plus'></i>
          <% end %>
        <% end %>
        <span id="post_<%=post.slug%>_votes"><%= total_votes(post) %></span>
        <% if logged_in? %>
          <%= link_to vote_post_path(post, vote: 'false'), method: 'POST', remote: true do %>
            <i class='icon-minus'></i>
          <% end %>
        <% end %>
        &nbsp
        <font size='5'>
          <%= link_to post.title, post_path(post) %>
        </font>
      </td>
      <td class='span1'>
        <% post.categories.each do |category| %>
          <div class="badge">
            <%= link_to "#{category.name}", category_path(category) %>
          </div>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class='span2'>
        <%= "Created by #{post.creator.username} at #{format_timestamp(post.created_at)}" %>
      </td>
      <td class='span1'>
        <%= link_to "#{post.comments.size} comments", post_path(post) %>
      </td>
    </tr>
  </table>
<% end %>

app/views/posts/new.html.erb
<h3> New Post! </h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<% @post.categories.each do |category| %>
  <span class="badge">
    <%= link_to "#{category.name}", category_path(category) %>
  </span>
<% end %>

<h3> <%= link_to @post.title, format_url(@post.url) %> </h3>

<p> <%= @post.description %> </p>

<p> <%= "Create at #{format_timestamp(@post.created_at)} by #{@post.creator.username}" %>

<% if update_access(@post) or current_user.admin? %>
  <p> <%= link_to "Edit Post", edit_post_path(@post) %> </p>
<% end %>

<hr />

<% if logged_in? %>
  <h4> Add New Comment </h4>

  <%= render 'shared/errors', obj: @comment %>

  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body %>
    <br />
    <%= f.submit %>
  <% end %>
<% end %>

<hr />

<h4> Comments </h4>

<% @post.comments.each do |comment| %>
  <table class='table'>
    <tr class='info'>
      <td class='span1'>
        <% if logged_in? %>
          <%= link_to vote_post_comment_path(@post, comment, vote: 'true'), method: 'POST', remote: true do %>
            <i class='icon-plus'></i>
          <% end %>
        <% end %>
        <span id="comment_<%= comment.id %>_votes"><%= total_votes(comment) %></span>
        <% if logged_in? %>
          <%= link_to vote_post_comment_path(@post, comment, vote: 'false'), method: 'POST', remote: true do %>
            <i class='icon-minus'></i>
          <% end %>
        <% end %>
        &nbsp
        <%= comment.body %> 
      </td>

      <td class='span1'>
        <%= "by #{comment.creator.username} at #{format_timestamp(comment.created_at)}" %>
      </td>
    </tr>
  </div>
<% end %>

app/views/posts/vote.js.erb
$("#post_<%= @post.slug %>_votes").html("<%= total_votes(@post) %>")

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h5> Save validation failed! </h5>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br />
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br />
  <%= f.label :timezone %>
  <%= f.time_zone_select :timezone, ActiveSupport::TimeZone.us_zones %>
  <br /> 
  <%= f.submit @user.new_record? ? "Register" : "Update Profile" %>
<% end %>

app/views/users/edit.html.erb
<h3>Update Profile</h3>

<%= render 'form' %>

app/views/users/new.html.erb
<h3>Register New User</h3>

<%= render 'form' %>